spring:
  datasource:
    url: jdbc:mysql://47.105.103.198:3306/synnex
    username: jerry
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
#mybatis的别名的配置
mybatis:
  type-aliases-package: com.synnex.springboot.domain

